sudo: false
language: ruby
rvm:
- '2.0'
- '2.1'
- '2.2'
- 'jruby-9.0.4.0'
jdk: oraclejdk8
script: bundle exec rspec spec && bundle exec rake pact:verify && bundle exec cucumber features && cd src/flapjack && go test -v
env: GOPATH=$TRAVIS_BUILD_DIR
gemfile: Gemfile
cache: bundler
services:
- redis-server
before_script:
- mkdir -p ./log
before_install:
- git submodule update --init --recursive
- gem uninstall bundler -v 1.11.0 # platform bug in bundler 1.11.0
- gem install bundler -v 1.10.6
install:
- go get github.com/garyburd/redigo/redis
- go get github.com/go-martini/martini
- go get gopkg.in/alecthomas/kingpin.v2
- go get github.com/oguzbilgic/pandik
- bundle install
notifications:
  irc:
    channels:
    - irc.freenode.net#flapjack
    template:
    - "%{message} %{repository}#%{build_number} (%{branch} - %{commit} : %{author})"
  slack:
    secure: OlXm5ljaX0xAR8wHEeODXUrL9r++LmBZIj/lZbJTJ0HUSUe11evYDN8NXAwzUCP57EGeVqV94m7uoIZzvknunrs4zPlNDAbTIGkSZ+ahemBYfQmlH54PYbPQWm0mrkN6NXgzn3e6CPkQIZPCWDA+/iq5oRl6ZZtIEmoa41KrUh0=
